### ISSUE TITLE
Order of sections, missing buttons and colours in data privacy

### ISSUE THREAD

**Issue by carloscorrales** [fiwoo-platform/mobile-apps#2]
Please, use the corporative colours, the background in dark grey is not pretty. Moreover, follow the same order for the sections that we have in the platform. Divide in Personal Data and Sensitive Data, and follow the same order in the sections. For instance, in personal data:

Name
Surname
Email
Telephone
Gender
Date of birth

Also the buttons for Remove Historics, Remove Device Data and Forget Me are missing

**Comment by jordiJIG** [comment]
Solved
